GET http://localhost:3000/users

###
GET http://localhost:3000/users/65c97e7fcf745ba5c5697222

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031",
    "website": "http://hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  }

###
PATCH http://localhost:3000/users/65c97e7fcf745ba5c5697222
Content-Type: application/json

{
  "username": "JohnDoe",
  "email": "john.doe@example.com"
}

###
DELETE http://localhost:3000/users/65c97e7fcf745ba5c5697222

###